
all:
	$(info "Please use 'make timeTest' or 'make example'")

timeTest:
	g++ -std=c++11 measurements.cpp simple-time-stats/DataPoint.cpp simple-time-stats/Meter.cpp -o timeTest

example:
	g++ -std=c++11 example.cpp simple-time-stats/DataPoint.cpp simple-time-stats/Meter.cpp -o example
